#------------------------------------------------------------
# Directories
#------------------------------------------------------------
WebContent.dir=./WebContents

build.dir=./build
src.dir=./src
class.dir=./classes
// change this dir to your local was dir
target.WebContent.dir=D:/apache-tomcat-5.5.29/webapps
// change this dir to your GlueSDK dir
GlueSDK.dir=D:/ux/tools/eclipse_unionsteel/users/GlueSDK

WEB_NAME=C10
APP_NAME=C10
JAR_NAME=C10Batch
project_version=1.0.0

// Dev. Server FTP Connection Information
devServer.user=mesuser
devServer.password=mesuser()
devServer.serverIp=210.1.1.139
devServer.scmdir=/APP/WAS/UBMWD/APP/C10

// Test Server FTP Connection Information
testServer.user=tstwas
testServer.password=tstwas!!
testServer.serverIp=210.1.1.138
testServer.scmdir=/APP/WAS/UBMWQ/APP/C10

// Real Server FTP Connection Information
realServer.user=uswas
realServer.password=US_meap9
realServer.serverIp=210.1.1.137
realServer.scmdir=/APP/WAS/UBMWP/APP/C10
